apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8090'
spec:
  selector: 
    app: jenkins
  type: NodePort  
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32000